### ISSUE TITLE
There is no code.

### ISSUE THREAD

**Issue by FranDieMaschine** [PacktPublishing/The-Future-of-Finance-with-ChatGPT-and-PowerBI#1]
After I bought the e-book, I am trying to download the code but there is no file.
Please, could you upload them?

**Comment by bsingha27** [comment]
Hi, 
All the Python code has been uploaded. To make it more organized and accessible, we've organized the code by chapter. Each chapter has its own branch.
Feel free to navigate to the repository and switch between branches to access the code for the specific chapter you're interested in.
